version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - servervol:/serverdata
    networks:
      - my_network
    ports:
      - "8000:8000"
    image: dice_devops_final_server  

volumes:
  servervol:

networks:
  my_network:
    external: true
