name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    
    - name: Build Docker Compose services
      run: |
        docker-compose build

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.39.1/trivy_0.39.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.39.1_Linux-64bit.deb

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        for service in $(docker-compose config --services); do
            # Get the image name as defined in docker-compose.yml
            image_name=$(docker-compose config | grep "image:" | awk -F: '{print $2}' | tr -d ' ')
            # Tag and push the image
            docker tag ${image_name} ${{ secrets.DOCKER_HUB_USERNAME }}/$image_name:latest
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$image_name:latest
          done
    